export const API_BASE_URL = "https://v2.api.noroff.dev";
export const API_AUTH = "/auth";
export const API_REGISTER = "/register";
export const API_LOGIN = "/login";
export const API_CREATE_KEY = "/create-api-key";
export const API_KEY = "15068765-9d50-4895-b37f-8df955555c36";
export const API_SOCIAL = "/social";
export const POSTS = "/posts";
export const DETAILS = "?_author=true&_comments=true&_reactions=true";
